name: pr-input_tower

on:
  pull_request:
    types: [opened, edited]

  workflow_dispatch:
    inputs:
      tower:
        description: 'Tower CAE | PROD'
        type: choice
        options:
          - CAE
          - PROD
      PR_branch:
        description: 'Branch targeted by the PR'
        default: 'master'
        required: true
        type: string

permissions:
  id-token: write
  contents: write
  pull-requests: write

jobs:
  pr-input_tower:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.tower || 'CAE' }}  # Default to CAE if no input
    env:
      INPUT_USER_ENV: ${{ github.event.inputs.tower || 'CAE' }}  # Default to CAE if no input
      PR_BRANCH: ${{ github.event.inputs.PR_branch }}
      USER_API: ${{ vars.USER_API }}

    steps:
      - uses: actions/checkout@v4

      - name: Test Var in ENV
        run: | 
          echo "This is the configured user: ${{ env.USER_API }}"
          echo "This is the 2nd configured user: $USER_API"
          echo "This is the branch ${{ env.PR_BRANCH }}"
          echo "This is the environment: $INPUT_USER_ENV"

      # This step adds a label to the PR based on the 'INPUT_USER_ENV' value and sets the color
      - name: Add label to PR
        if: ${{ env.INPUT_USER_ENV != '' }}
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const envLabel = "${{ env.INPUT_USER_ENV }}";
            const prNumber = context.payload.pull_request.number;
            const color = envLabel === 'CAE' ? '00ff00' : 'ff0000';  // Green for CAE, Red for PROD
            console.log(`Adding label '${envLabel}' with color '${color}' to PR #${prNumber}`);
            // Create or update the label with the correct color
            await github.rest.issues.createLabel({
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: envLabel,
              color: color
            }).catch(async (error) => {
              if (error.status === 422) {
                // Label already exists, update the color
                await github.rest.issues.updateLabel({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  name: envLabel,
                  color: color
                });
              } else {
                throw error;
              }
            });
            // Add the label to the PR
            await github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: prNumber,
              labels: [envLabel]
            });
      
      - name: Execute a script
        id: execute_script
        run: |
            echo "Running the script"
            python3 ./scripts/clean-csvFiles.py ./ipgroups/data/data.csv
        continue-on-error: true

      - name: Set Result Message
        id: set_message
        run: |
          if [ ${{ steps.execute_script.outcome }} == 'success' ]; then
            echo "::set-output name=message::Script execution succeeded at commit ${{ github.sha }}"
          else
            echo "::set-output name=message::Script execution failed with error: ${{ steps.execute_script.conclusion }}"
          fi


    #   - name: Check for all Files Changes
    #     run: |
    #         git fetch
    #         echo 'executing git diff'
    #         git diff --name-only --diff-filter=ACMRT ${{ github.event.pull_request.base.sha }} ${{ github.sha }} | xargs
    #         files_changed=$(git diff --name-only --diff-filter=ACMRT ${{ github.event.pull_request.base.sha }} ${{ github.sha }} | xargs)
           
    #         echo -e "\n Files Changed: $files_changed"
      
    #   - name: Check for only CSV Files Changes
    #     run: |
    #       echo 'Executing git diff to find changes...'
    #       git fetch --depth=1
    #       CSV_FILES_CHANGED=$(git diff --name-only --diff-filter=ACMRT ${{ github.event.pull_request.base.sha }} ${{ github.sha }} | grep 'ipgroups/.*\.csv')
    #       echo "CSV Files Changed in ipgroups folder:"
    #       echo "$CSV_FILES_CHANGED"
       
    #   - name: Check for Changes in one cvs Files
    #     id: status_changed
    #     shell: bash
    #     run: |
            
    #         if [[ $(git diff --name-only ${{ github.event.pull_request.base.sha }}...${{ github.event.pull_request.head.sha }} sample_ip.csv) ]]; then
    #             echo "Changes detected in sample_ip.csv"
    #             echo "file_changed=true" >> $GITHUB_OUTPUT
    #         else
    #           echo "No changes detected in sample_ip.csv"
    #           echo "file_changed=false" >> $GITHUB_OUTPUT
    #         fi

  #     - name: Generate Address group from csv file
  #       if: ${{ steps.status_changed.outputs.file_changed }} == 'true'
  #       run: |
  
  #           python --version    
  #           python3 ./convert_cvs_to_yaml.py
  #           echo -e '>>>>> new group Address: \n'
  #           cat ./groups.yaml
            
  #     - name:  create new PR for Validation
  #       if: steps.status_changed.outputs.file_changed == 'true'
  #       env:
  #           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #       run: |
  
  #         echo "Changes detected, preparing to update branch."
  #         git config user.name "secops-ipgroup-management"
  #         git config user.email "your-email@example.com"

  #         git fetch origin
  #         git checkout -B botFMG origin/botFMG || git checkout -b botFMG
  #         git reset --hard ${{ github.event.pull_request.head.sha }}
  #         git push -f origin botFMG


  # tests_on_tower:
  #   needs: pr-input_tower
  #   runs-on: ubuntu-latest
  #   steps:
  #       - name: Checkout user branch
  #         uses: actions/checkout@v4
  #         with:
  #           ref: 'botFMG'
                  
  #       - name: Run security tests
  #         run: |
  #               # Add commands to run your security tests here
  #               echo "Running security tests..."
  #               ls -lhR
  #               # cat ./groups.yaml